### ISSUE TITLE
Empty space on jellyflix in tv shows

### ISSUE THREAD

**Issue by tonystank420** [prayag17/JellyFlix#26]
There is a ton of empty space which means I have to scroll down to select seasons. Is this a bug and are there any plans to fix it

![image](https://user-images.githubusercontent.com/98456024/151139026-2ce14d09-139d-4a27-a253-3d075e65eaeb.png)

![image](https://user-images.githubusercontent.com/98456024/151139106-54c11a05-f171-445c-8033-98b8a40ae158.png)

**Comment by prayag17** [comment]
That is not a bug that is how it is meant to be

**Comment by tonystank420** [comment]
Understood. Is there any way for me to change it? Thanks

**Comment by prayag17** [comment]
```css
.detailPagePrimaryContent {
    min-height: fit-content !important;
}
```
