### ISSUE TITLE
(Desktop) Quick actions overlapping view progress

### ISSUE THREAD

**Issue by Matix-Media** [prayag17/JellyFlix#58]
Platform: Desktop

Following issue: https://i.imgur.com/2PQwkn5.png

**Comment by Matix-Media** [comment]
Quick and dirty fix
```css
.cardOverlayButton-br {
    margin-bottom: 15px;
    gap: 5px;
}
```
